application:
  name: micro-go-template
  version: 0.0.1
  port: 8888
  mode: dev #dev|prod
  cors:
    allowedHost: localhost, https://labstack.com, https://labstack.net

db.configs:
  username: root
  password: root
  host: localhost
  port: 3306
  database: test_ent
  maxIdleConn: 10
  maxOpenConn: 100

outbound:
  quotes:
    get-url: https://programming-quotesapi.vercel.app/api/random
    post-url: https://en8trqq30hty3.x.pipedream.net/


cache:
  configs:
    redis:
      host: localhost
      port: 6379
      username:
      password:
      db: 0
      poolSize: 10
  ttl:
    short-period: 3h
    medium-period: 24h
    long-period: 3d

